service: serverless-documentation

plugins:
  - serverless-apigw-binary
  - serverless-domain-manager
  - serverless-offline

provider:
  name: aws
  region: ap-southeast-2
  stage: ${opt:stage, 'dev'}
  runtime: nodejs12.x
  environment:
    NODE_ENV: production
    

custom:
  customDomain:
    domainName: ${self:service}.robmellett.dev
    basePath: ''
    # stage: ${self:provider.stage}
    createRoute53Record: false
    # endpointType: 'regional'
    # securityPolicy: tls_1_2
    # apiType: http
    # region: ${self:provider.region}

  apigwBinary:
    types:
      - 'image/*'
  nuxt:
    version: v${file(./package.json):version}
    # Asset Path https://my-nuxt-project-prod.s3.amazonaws.com/v1.3.1/
    bucketName: ${self:service}-${self:provider.stage}

resources:
  Resources:
    AssetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.nuxt.bucketName}
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
              - GET
              - HEAD
              AllowedOrigins:
              - https://${self:service}.robmellett.dev

functions:
  web:
    timeout: 30
    handler: handler.nuxt
    events:
      # lambda warmer
      # - schedule: rate(5 minutes)
      - http: ANY /
      - http: ANY /{proxy+}